// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrisense.Nutrisense.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Nutrisense.Nutrisense.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630190656_Subscriptions_StripeCustomerId")]
    partial class Subscriptions_StripeCustomerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.ActivityWearable.Domain.Model.Aggregates.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("activity_type");

                    b.Property<decimal>("CaloriesBurned")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("calories_burned");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("intensity");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("logged_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_activity_logs");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_activity_logs_user_date");

                    b.ToTable("activity_logs");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.ActivityWearable.Domain.Model.Aggregates.WearableConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("AuthorizedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("authorized_at");

                    b.Property<bool>("AutoSyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_sync_enabled");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_wearable_connections");

                    b.HasIndex("UserId", "Provider")
                        .HasDatabaseName("ix_wearable_connections_user_provider");

                    b.ToTable("wearable_connections");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.AnalyticsReporting.Domain.Model.Aggregates.UserAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int")
                        .HasColumnName("current_streak");

                    b.Property<decimal?>("LastAdherenceScore")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("last_adherence_score");

                    b.Property<string>("LastLogDate")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("last_log_date");

                    b.Property<DateTimeOffset?>("LastProgressCalculatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_progress_calculated_at");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int")
                        .HasColumnName("longest_streak");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeeklyCompletionRate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("weekly_completion_rate");

                    b.HasKey("Id")
                        .HasName("p_k_user_analytics");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_analytics_records_user_id");

                    b.ToTable("user_analytics");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.AnalyticsReporting.Domain.Model.Entities.ProgressSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("AdherenceScore")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("adherence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_complete");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_calories");

                    b.Property<decimal>("TotalCarbsG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_carbs_g");

                    b.Property<decimal>("TotalFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_fat_g");

                    b.Property<decimal>("TotalProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_protein_g");

                    b.Property<int>("UserAnalyticsId")
                        .HasColumnType("int")
                        .HasColumnName("user_analytics_id");

                    b.HasKey("Id")
                        .HasName("p_k_progress_snapshots");

                    b.HasIndex("UserAnalyticsId", "Date")
                        .HasDatabaseName("ix_progress_snapshots_analytics_date");

                    b.ToTable("progress_snapshots");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("activity_level");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("biological_sex");

                    b.Property<string>("BmiCategory")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bmi_category");

                    b.Property<decimal?>("BmiValue")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bmi_value");

                    b.Property<decimal?>("Bmr")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("bmr");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_birth");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<int?>("MacroCalories")
                        .HasColumnType("int")
                        .HasColumnName("macro_daily_calories");

                    b.Property<decimal?>("MacroCarbsG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_carbs_g");

                    b.Property<decimal?>("MacroFatG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_fat_g");

                    b.Property<decimal?>("MacroFiberG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_fiber_g");

                    b.Property<decimal?>("MacroProteinG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_protein_g");

                    b.Property<decimal?>("Tdee")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("tdee");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_body_metrics");

                    b.HasAlternateKey("UserId")
                        .HasName("a_k_body_metrics_user_id");

                    b.ToTable("body_metrics", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("measured_at");

                    b.Property<decimal>("NeckCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("neck_cm");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WaistCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("waist_cm");

                    b.HasKey("Id")
                        .HasName("p_k_body_measurements");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_body_measurements_user_id");

                    b.ToTable("body_measurements", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<decimal>("CaloricAdjustment")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("caloric_adjustment");

                    b.Property<decimal>("CarbsTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("carbs_target_g");

                    b.Property<int>("DailyCalorieTarget")
                        .HasColumnType("int")
                        .HasColumnName("daily_calorie_target");

                    b.Property<decimal>("FatTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("fat_target_g");

                    b.Property<decimal>("FiberTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("fiber_target_g");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("goal");

                    b.Property<decimal>("ProteinTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("protein_target_g");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("datetime")
                        .HasColumnName("set_at");

                    b.Property<decimal>("StartWeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("start_weight_kg");

                    b.Property<decimal>("TargetWeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("target_weight_kg");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeeklyRateKg")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("weekly_rate_kg");

                    b.HasKey("Id")
                        .HasName("p_k_user_goals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_goals_user_id");

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("logged_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("p_k_weight_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_weight_logs_user_id");

                    b.ToTable("weight_logs", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_reset_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("activity_level");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoalIntent")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("goal_intent");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("medical_conditions");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PreferredUnits")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("preferred_units");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.DietaryRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Restriction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("restriction");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_dietary_restrictions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_dietary_restrictions_user_id");

                    b.ToTable("dietary_restrictions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_label");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_sessions_user_id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.NutritionTracking.Domain.Model.Aggregates.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("calories_per100g");

                    b.Property<decimal>("CarbsPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carbs_per100g");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Other")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("external_id");

                    b.Property<decimal>("FatPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fat_per100g");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fiber_per100g");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("key");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_es");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("protein_per100g");

                    b.Property<string>("Restrictions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("restrictions");

                    b.Property<decimal>("ServingSizeG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("serving_size_g");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("serving_unit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<decimal>("SugarPer100g")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sugar_per100g");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_foods");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_foods_external_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_foods_key");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.NutritionTracking.Domain.Model.Aggregates.NutritionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("calories");

                    b.Property<decimal>("CarbsG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("carbs_g");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<decimal>("FatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fat_g");

                    b.Property<decimal>("FiberG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fiber_g");

                    b.Property<int>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    b.Property<string>("FoodNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("food_name_en");

                    b.Property<string>("FoodNameEs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("food_name_es");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("logged_at");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("meal_type");

                    b.Property<decimal>("ProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("protein_g");

                    b.Property<decimal>("QuantityG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantity_g");

                    b.Property<decimal?>("ScanConfidence")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("scan_confidence");

                    b.Property<string>("ScanImageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("scan_image_uri");

                    b.Property<string>("ScanType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("scan_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.Property<decimal>("SugarG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sugar_g");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_nutrition_logs");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_nutrition_logs_user_date");

                    b.ToTable("nutrition_logs");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("key");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lng");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_es");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("p_k_cities");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_key");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.IngredientCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("default_unit");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    b.Property<decimal?>("GramsPerUnit")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("grams_per_unit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_es");

                    b.HasKey("Id")
                        .HasName("p_k_ingredient_catalog_items");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredient_catalog_items_key");

                    b.ToTable("ingredient_catalog_items");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.LocationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentCityId")
                        .HasColumnType("int")
                        .HasColumnName("current_city_id");

                    b.Property<int?>("HomeCityId")
                        .HasColumnType("int")
                        .HasColumnName("home_city_id");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_manual_override");

                    b.Property<bool>("LocationPermissionGranted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("location_permission_granted");

                    b.Property<bool>("TravelModeActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("travel_mode_active");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_location_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_location_preferences_user_id");

                    b.ToTable("location_preferences");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.Pantry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_pantries");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_pantries_user_id");

                    b.ToTable("pantries");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("goal_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_es");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int")
                        .HasColumnName("prep_time_minutes");

                    b.Property<string>("RestrictionsConflict")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("restrictions_conflict");

                    b.Property<int>("Servings")
                        .HasColumnType("int")
                        .HasColumnName("servings");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_calories");

                    b.Property<decimal>("TotalCarbsG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_carbs_g");

                    b.Property<decimal>("TotalFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_fat_g");

                    b.Property<decimal>("TotalFiberG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_fiber_g");

                    b.Property<decimal>("TotalProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_protein_g");

                    b.HasKey("Id")
                        .HasName("p_k_recipes");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_recipes_key");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.RecommendationCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("badge");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("ContextLabelEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("context_label_en");

                    b.Property<string>("ContextLabelEs")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("context_label_es");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedCalories")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_calories");

                    b.Property<decimal>("EstimatedCarbsG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_carbs_g");

                    b.Property<decimal>("EstimatedFatG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_fat_g");

                    b.Property<decimal>("EstimatedProteinG")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("estimated_protein_g");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    b.Property<string>("FoodNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("food_name_en");

                    b.Property<string>("FoodNameEs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("food_name_es");

                    b.Property<string>("GoalType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("goal_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("RestrictionsConflict")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("restrictions_conflict");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("WeatherType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("weather_type");

                    b.HasKey("Id")
                        .HasName("p_k_recommendation_cards");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recommendation_cards_user_id");

                    b.ToTable("recommendation_cards");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Entities.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("IngredientCatalogItemId")
                        .HasColumnType("int")
                        .HasColumnName("ingredient_catalog_item_id");

                    b.Property<int>("PantryId")
                        .HasColumnType("int")
                        .HasColumnName("pantry_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("p_k_pantry_items");

                    b.HasIndex("PantryId")
                        .HasDatabaseName("i_x_pantry_items_pantry_id");

                    b.ToTable("pantry_items");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Entities.RecipeIngredientItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IngredientCatalogItemId")
                        .HasColumnType("int")
                        .HasColumnName("ingredient_catalog_item_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("p_k_recipe_ingredient_items");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("i_x_recipe_ingredient_items_recipe_id");

                    b.ToTable("recipe_ingredient_items");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("brand");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cardholder_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int")
                        .HasColumnName("expiry_month");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int")
                        .HasColumnName("expiry_year");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("last_four");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_payment_method_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_payment_methods");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("features");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("key");

                    b.Property<decimal?>("PriceAnnual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_annual");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_monthly");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_plans");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_plans_key");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("billing_period");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastPlanChangeAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_plan_change_at");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("datetime")
                        .HasColumnName("period_start");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plan_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_subscriptions");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Entities.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("user_subscription_id");

                    b.HasKey("Id")
                        .HasName("p_k_payment_records");

                    b.HasIndex("UserSubscriptionId")
                        .HasDatabaseName("i_x_payment_records_user_subscription_id");

                    b.ToTable("payment_records", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.AnalyticsReporting.Domain.Model.Entities.ProgressSnapshot", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.AnalyticsReporting.Domain.Model.Aggregates.UserAnalytics", null)
                        .WithMany("ProgressSnapshots")
                        .HasForeignKey("UserAnalyticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_progress_snapshots_user_analytics_user_analytics_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", null)
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_body_measurements_body_metrics_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.UserGoal", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", null)
                        .WithMany("UserGoals")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_goals_body_metrics_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.WeightLog", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", null)
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weight_logs_body_metrics_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.DietaryRestriction", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany("DietaryRestrictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_dietary_restrictions_users_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.UserSession", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_sessions_users_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Entities.PantryItem", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.Pantry", null)
                        .WithMany("Items")
                        .HasForeignKey("PantryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pantry_items_pantries_pantry_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Entities.RecipeIngredientItem", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_recipe_ingredient_items_recipes_recipe_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Entities.PaymentRecord", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.UserSubscription", null)
                        .WithMany("PaymentRecords")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payment_records_user_subscriptions_user_subscription_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.AnalyticsReporting.Domain.Model.Aggregates.UserAnalytics", b =>
                {
                    b.Navigation("ProgressSnapshots");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("UserGoals");

                    b.Navigation("WeightLogs");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Navigation("DietaryRestrictions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.Pantry", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.SmartRecommendations.Domain.Model.Aggregates.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Navigation("PaymentRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
