// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrisense.Nutrisense.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Nutrisense.Nutrisense.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620001754_Subscriptions_InitialCreate")]
    partial class Subscriptions_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("activity_level");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("biological_sex");

                    b.Property<string>("BmiCategory")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bmi_category");

                    b.Property<decimal?>("BmiValue")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bmi_value");

                    b.Property<decimal?>("Bmr")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("bmr");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_birth");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<int?>("MacroCalories")
                        .HasColumnType("int")
                        .HasColumnName("macro_daily_calories");

                    b.Property<decimal?>("MacroCarbsG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_carbs_g");

                    b.Property<decimal?>("MacroFatG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_fat_g");

                    b.Property<decimal?>("MacroFiberG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_fiber_g");

                    b.Property<decimal?>("MacroProteinG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("macro_protein_g");

                    b.Property<decimal?>("Tdee")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("tdee");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_body_metrics");

                    b.HasAlternateKey("UserId")
                        .HasName("a_k_body_metrics_user_id");

                    b.ToTable("body_metrics", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("measured_at");

                    b.Property<decimal>("NeckCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("neck_cm");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WaistCm")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("waist_cm");

                    b.HasKey("Id")
                        .HasName("p_k_body_measurements");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_body_measurements_user_id");

                    b.ToTable("body_measurements", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<decimal>("CaloricAdjustment")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("caloric_adjustment");

                    b.Property<decimal>("CarbsTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("carbs_target_g");

                    b.Property<int>("DailyCalorieTarget")
                        .HasColumnType("int")
                        .HasColumnName("daily_calorie_target");

                    b.Property<decimal>("FatTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("fat_target_g");

                    b.Property<decimal>("FiberTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("fiber_target_g");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("goal");

                    b.Property<decimal>("ProteinTargetG")
                        .HasColumnType("decimal(6,1)")
                        .HasColumnName("protein_target_g");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("datetime")
                        .HasColumnName("set_at");

                    b.Property<decimal>("StartWeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("start_weight_kg");

                    b.Property<decimal>("TargetWeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("target_weight_kg");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeeklyRateKg")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("weekly_rate_kg");

                    b.HasKey("Id")
                        .HasName("p_k_user_goals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_goals_user_id");

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("logged_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("p_k_weight_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_weight_logs_user_id");

                    b.ToTable("weight_logs", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("activity_level");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoalIntent")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("goal_intent");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("medical_conditions");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PreferredUnits")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("preferred_units");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.DietaryRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Restriction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("restriction");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_dietary_restrictions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_dietary_restrictions_user_id");

                    b.ToTable("dietary_restrictions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_label");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_sessions_user_id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("brand");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cardholder_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("int")
                        .HasColumnName("expiry_month");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("int")
                        .HasColumnName("expiry_year");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("last_four");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_payment_method_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_payment_methods");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("features");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("key");

                    b.Property<decimal?>("PriceAnnual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_annual");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_monthly");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_plans");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_plans_key");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("billing_period");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastPlanChangeAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_plan_change_at");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("datetime")
                        .HasColumnName("period_start");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plan_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_subscriptions");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Entities.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("longtext")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("user_subscription_id");

                    b.HasKey("Id")
                        .HasName("p_k_payment_records");

                    b.HasIndex("UserSubscriptionId")
                        .HasDatabaseName("i_x_payment_records_user_subscription_id");

                    b.ToTable("payment_records", (string)null);
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", null)
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_body_measurements_body_metrics_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.UserGoal", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", null)
                        .WithMany("UserGoals")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_goals_body_metrics_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Entities.WeightLog", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", null)
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weight_logs_body_metrics_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.DietaryRestriction", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany("DietaryRestrictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_dietary_restrictions_users_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.UserSession", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_sessions_users_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Entities.PaymentRecord", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.UserSubscription", null)
                        .WithMany("PaymentRecords")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payment_records_user_subscriptions_user_subscription_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.BodyHealthMetrics.Domain.Model.Aggregates.BodyMetrics", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("UserGoals");

                    b.Navigation("WeightLogs");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Navigation("DietaryRestrictions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.Subscriptions.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Navigation("PaymentRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
