// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrisense.Nutrisense.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace Nutrisense.Nutrisense.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619224057_IAM_InitialCreate")]
    partial class IAM_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("activity_level");

                    b.Property<string>("BiologicalSex")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoalIntent")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("goal_intent");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("medical_conditions");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("PreferredUnits")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("preferred_units");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.DietaryRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Restriction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("restriction");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_dietary_restrictions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_dietary_restrictions_user_id");

                    b.ToTable("dietary_restrictions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_label");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_sessions_user_id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.DietaryRestriction", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany("DietaryRestrictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_dietary_restrictions_users_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Entities.UserSession", b =>
                {
                    b.HasOne("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_sessions_users_user_id");
                });

            modelBuilder.Entity("Nutrisense.Nutrisense.Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Navigation("DietaryRestrictions");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
